# This file is part of the Sylius sandbox Sylius\Sandbox.
# (c) Paweł Jędrzejewski

imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: database.yml }

framework:
    default_locale: %sylius.locale%
    form: ~
    secret: %sylius.secret%
    csrf_protection:
        enabled: true
    router:        { resource: "%kernel.root_dir%/config/routing/base.yml" }
    validation:    { enabled: true, enable_annotations: true }
    translator:    { fallback: %sylius.locale% }
    templating:    { engines: ['twig', 'php'] }
    session:
        name: SYLIUS_SANDBOX_SESSION
        lifetime: 72000

twig:
    form:
        resources:
            - 'SandboxCoreBundle::forms.html.twig'
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

assetic:
    debug:          %kernel.debug%
    use_controller: false
    read_from:      %kernel.root_dir%/../public

swiftmailer:
    disable_delivery: %kernel.debug%
    transport: %sylius.mailer.transport%
    host:      %sylius.mailer.host%
    username:  %sylius.mailer.user%
    password:  %sylius.mailer.password%

stof_doctrine_extensions:
    default_locale: %sylius.locale%
    orm:
        default:
            tree: true
            sluggable: true
            timestampable: true
            softdeleteable: true

avalanche_imagine:
    source_root:  %kernel.root_dir%/../public
    web_root: %kernel.root_dir%/../public
    cache_prefix: media/cache
    filters:
        frontend_medium:
            type: thumbnail
            options: { size: [220, 180], mode: outbound }
        backend_mini:
            type: thumbnail
            options: { size: [90, 60], mode: outbound }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Sylius\Sandbox\Bundle\CoreBundle\Entity\User

fos_comment:
    db_driver: orm
    class:
        model:
            comment: Sylius\Sandbox\Bundle\CoreBundle\Entity\Comment
            thread: Sylius\Sandbox\Bundle\CoreBundle\Entity\Thread
    acl: true
    service:
        acl:
            thread: fos_comment.acl.thread.roles
            comment: fos_comment.acl.comment.roles
            vote: fos_comment.acl.vote.roles
    acl_roles:
        comment:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_SYLIUS_ADMIN
            delete: ROLE_SYLIUS_ADMIN
        thread:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_SYLIUS_ADMIN
            delete: ROLE_SYLIUS_ADMIN
        vote:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_SYLIUS_ADMIN
            delete: ROLE_SYLIUS_ADMIN

sylius_assortment:
    driver: doctrine/orm
    api: true
    classes:
        model:
            product: Sylius\Sandbox\Bundle\CoreBundle\Entity\Product
            variant: Sylius\Sandbox\Bundle\CoreBundle\Entity\Variant\Variant
            property: Sylius\Sandbox\Bundle\CoreBundle\Entity\Property\Property
            product_property: Sylius\Sandbox\Bundle\CoreBundle\Entity\Property\ProductProperty
            prototype: Sylius\Sandbox\Bundle\CoreBundle\Entity\Prototype\Prototype
            option: Sylius\Sandbox\Bundle\CoreBundle\Entity\Option\Option
            option_value: Sylius\Sandbox\Bundle\CoreBundle\Entity\Option\OptionValue
        form:
            type:
                product: Sylius\Sandbox\Bundle\CoreBundle\Form\Type\ProductType
                variant: Sylius\Sandbox\Bundle\CoreBundle\Form\Type\VariantType

sylius_categorizer:
    driver: doctrine/orm
    catalogs:
        assortment:
            property: "products"
            model: Sylius\Sandbox\Bundle\CoreBundle\Entity\ProductCategory
            form: sylius_sandbox_assortment_category
            templates:
                backend: SandboxAssortmentBundle:Backend/Category:%s.html.twig
                frontend: SandboxAssortmentBundle:Frontend/Category:%s.html.twig
        blog:
            property: "posts"
            model: Sylius\Sandbox\Bundle\CoreBundle\Entity\PostCategory
            templates:
                backend: SandboxBloggerBundle:Backend/Category:%s.html.twig
                frontend: SandboxBloggerBundle:Frontend/Category:%s.html.twig

sylius_cart:
    driver: doctrine/orm
    operator: sylius_sandbox_cart.operator
    resolver: sylius_sandbox_cart.resolver
    classes:
        model:
            cart: Sylius\Sandbox\Bundle\CoreBundle\Entity\Cart
            item: Sylius\Sandbox\Bundle\CoreBundle\Entity\CartItem
        form:
            type:
                item: Sylius\Sandbox\Bundle\CoreBundle\Form\Type\ItemType

sylius_blogger:
    driver: doctrine/orm
    classes:
        model:
            post: Sylius\Sandbox\Bundle\CoreBundle\Entity\Post
        form:
            type:
                post: Sylius\Sandbox\Bundle\CoreBundle\Form\Type\PostType

sylius_sales:
    driver: doctrine/orm
    classes:
        model:
            order: Sylius\Sandbox\Bundle\CoreBundle\Entity\Order
            line_item: Sylius\Sandbox\Bundle\CoreBundle\Entity\LineItem
        form:
            type:
                order: Sylius\Sandbox\Bundle\CoreBundle\Form\Type\OrderType
                line_item: Sylius\Sandbox\Bundle\CoreBundle\Form\Type\LineItemType

sylius_addressing:
    driver: doctrine/orm
    classes:
        model:
            address: Sylius\Sandbox\Bundle\CoreBundle\Entity\Address
        form:
            type:
                address: Sylius\Bundle\AddressingBundle\Form\Type\CommonAddressType

sylius_inventory:
    driver: doctrine/orm
    classes:
        model:
            iu: Sylius\Sandbox\Bundle\CoreBundle\Entity\InventoryUnit
