# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

sylius_sandbox_core_frontend_index:
    pattern: /
    defaults: { _controller: sylius_sandbox_core.controller.frontend.main:indexAction }

sylius_sandbox_core_frontend_post:
    prefix: /blog
    resource: @SandboxCoreBundle/Resources/config/routing/frontend/post.yml
