# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

sylius_sandbox_backend_address_new:
    pattern: /new
    defaults:
        _controller: sylius_addressing.controller.address:newAction
        _sylius.template: SandboxCoreBundle:Backend/Address:create.html.twig
    requirements:
        _method: GET

sylius_sandbox_backend_address_post:
    pattern: /
    defaults:
        _controller: sylius_addressing.controller.address:postAction
        _sylius.template: SandboxCoreBundle:Backend/Address:create.html.twig
        _sylius.redirect: sylius_sandbox_backend_address
    requirements:
        _method: POST

sylius_sandbox_backend_address_edit:
    pattern: /{id}/edit
    defaults:
        _controller: sylius_addressing.controller.address:editAction
        _sylius.template: SandboxCoreBundle:Backend/Address:update.html.twig
    requirements:
        _method: GET

sylius_sandbox_backend_address_put:
    pattern: /{id}
    defaults:
        _controller: sylius_addressing.controller.address:putAction
        _sylius.template: SandboxCoreBundle:Backend/Address:update.html.twig
        _sylius.redirect: sylius_sandbox_backend_address
    requirements:
        _method: PUT|POST

sylius_sandbox_backend_address_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius_addressing.controller.address:deleteAction
        _sylius.redirect: sylius_sandbox_backend_addresses
    requirements:
        _method: GET

sylius_sandbox_backend_addresses:
    pattern: /
    defaults:
        _controller: sylius_addressing.controller.address:getCollectionAction
        _sylius.template: SandboxCoreBundle:Backend/Address:list.html.twig
    requirements:
        _method: GET

sylius_sandbox_backend_address:
    pattern: /{id}
    defaults:
        _controller: sylius_addressing.controller.address:getAction
        _sylius.template: SandboxCoreBundle:Backend/Address:show.html.twig
    requirements:
        _method: GET
