# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

sylius_sandbox_core_backend_index:
    pattern: /
    defaults: { _controller: sylius_sandbox_core.controller.backend.main:indexAction }

sylius_sandbox_core_backend_address:
    prefix: /addresses
    resource: @SandboxCoreBundle/Resources/config/routing/backend/address.yml

sylius_sandbox_core_backend_post:
    prefix: /posts
    resource: @SandboxCoreBundle/Resources/config/routing/backend/post.yml
