# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

sylius_sandbox_backend_property_list:
    pattern: /
    defaults: 
        _controller: sylius_assortment.controller.property:getCollectionAction
        _sylius.template: SandboxCoreBundle:Backend/property:list.html.twig

sylius_sandbox_backend_property_create:
    pattern: /create
    defaults: 
        _controller: sylius_assortment.controller.property:createAction
        _sylius.template: SandboxCoreBundle:Backend/property:create.html.twig

sylius_sandbox_backend_property_update:
    pattern: /update
    defaults: 
        _controller: sylius_assortment.controller.property:updateAction
        _sylius.template: SandboxCoreBundle:Backend/property:update.html.twig

sylius_sandbox_backend_property_delete:
    pattern: /{id}/delete
    defaults: 
        _controller: sylius_assortment.controller.property:deleteAction

sylius_sandbox_backend_property_show:
    pattern: /{id}
    defaults: 
        _controller: sylius_assortment.controller.property:getAction
        _sylius.template: SandboxCoreBundle:Backend/property:show.html.twig
